---
title: "Assignments week 2"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Week2

**Create a GitHub repository to store your codes of assignment 2.1 and 2.2.** Use your group project repository for 2.3.

### Assignment 2.1 --  `dataRetrieval`

1. Add the [Santa Paula Creek](https://waterdata.usgs.gov/nwis/uv?site_no=11113500) gauge to exercise we did in class
2. What is the best way to query multiple sites using this R package?
3. Create a plot showing any stream flow response to the rain of last night (10/04). Determine at what time did the stream flow peaked (if any) at the two locations?

### Assignment 2.2 --  `metajam`

Finish the exercise we started during the lab session to use `metajam` to download the Alaskan household languages data from DataONE:

For rappel:

The data: https://doi.org/10.5063/F1N58JPP

1. Read the metadata 
2. Download the data `household_language.csv` using metajam
3. Read the data into R using metajam
4. Write a piece of code that will compute the percentage of Alaskan household speaking only English for the year 2009 to 2015
5. Create a plot to visualize this data


For inspiration Here is the code sample we started during the lab: https://brunj7.github.io/EDS-213-metadata/codes/metajam_session.html


**Push all your codes to a GitHub repository and add me (`brunj7`) as a collaborator to your repository.**



### Assignment 2.3 -- Use an API to retrieve data for your project

As your group project team:

1. Based and what we discussed this week, find an API that you could use to retrieve data you are using in your group project.

2. **In your Group project repository**, write a script to retrieve the data relying on this API. Don't forget to capture any information about how you found the data as well as any metadata in the Rmarkdown / jupyter notebook so an external user can understand the data set(s) and track their source / data provider. 


## Due date:

**Wed 10/13/2021 at 12PM (Noon)**

<br>
